# Generated by Django 4.2.3 on 2023-08-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Email_Address',
            field=models.EmailField(max_length=60, unique=True, verbose_name='email'),
        ),
    ]
